import type { Config } from "tailwindcss";
import tailwindTypography from "@tailwindcss/typography";
const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: {
          0: `hsl(var(--color-primary-0))`,
          5: `hsl(var(--color-primary-5))`,
          10: `hsl(var(--color-primary-10))`,
          15: `hsl(var(--color-primary-15))`,
          20: `hsl(var(--color-primary-20))`,
          25: `hsl(var(--color-primary-25))`,
          30: `hsl(var(--color-primary-30))`,
          35: `hsl(var(--color-primary-35))`,
          40: `hsl(var(--color-primary-40))`,
          45: `hsl(var(--color-primary-45))`,
          50: `hsl(var(--color-primary-50))`,
          55: `hsl(var(--color-primary-55))`,
          60: `hsl(var(--color-primary-60))`,
          65: `hsl(var(--color-primary-65))`,
          70: `hsl(var(--color-primary-70))`,
          75: `hsl(var(--color-primary-75))`,
          80: `hsl(var(--color-primary-80))`,
          85: `hsl(var(--color-primary-85))`,
          90: `hsl(var(--color-primary-90))`,
          95: `hsl(var(--color-primary-95))`,
          100: `hsl(var(--color-primary-100))`,
        },
        accent: {
          0: `hsl(var(--color-accent-0))`,
          5: `hsl(var(--color-accent-5))`,
          10: `hsl(var(--color-accent-10))`,
          15: `hsl(var(--color-accent-15))`,
          20: `hsl(var(--color-accent-20))`,
          25: `hsl(var(--color-accent-25))`,
          30: `hsl(var(--color-accent-30))`,
          35: `hsl(var(--color-accent-35))`,
          40: `hsl(var(--color-accent-40))`,
          45: `hsl(var(--color-accent-45))`,
          50: `hsl(var(--color-accent-50))`,
          55: `hsl(var(--color-accent-55))`,
          60: `hsl(var(--color-accent-60))`,
          65: `hsl(var(--color-accent-65))`,
          70: `hsl(var(--color-accent-70))`,
          75: `hsl(var(--color-accent-75))`,
          80: `hsl(var(--color-accent-80))`,
          85: `hsl(var(--color-accent-85))`,
          90: `hsl(var(--color-accent-90))`,
          95: `hsl(var(--color-accent-95))`,
          100: `hsl(var(--color-accent-100))`,
        },
        muted: {
          0: `hsl(var(--color-muted-0))`,
          5: `hsl(var(--color-muted-5))`,
          10: `hsl(var(--color-muted-10))`,
          15: `hsl(var(--color-muted-15))`,
          20: `hsl(var(--color-muted-20))`,
          25: `hsl(var(--color-muted-25))`,
          30: `hsl(var(--color-muted-30))`,
          35: `hsl(var(--color-muted-35))`,
          40: `hsl(var(--color-muted-40))`,
          45: `hsl(var(--color-muted-45))`,
          50: `hsl(var(--color-muted-50))`,
          55: `hsl(var(--color-muted-55))`,
          60: `hsl(var(--color-muted-60))`,
          65: `hsl(var(--color-muted-65))`,
          70: `hsl(var(--color-muted-70))`,
          75: `hsl(var(--color-muted-75))`,
          80: `hsl(var(--color-muted-80))`,
          85: `hsl(var(--color-muted-85))`,
          90: `hsl(var(--color-muted-90))`,
          95: `hsl(var(--color-muted-95))`,
          100: `hsl(var(--color-muted-100))`,
        },
      },
    },
  },
  plugins: [tailwindTypography],
};
export default config;
