import type { Metadata } from "next";
import "./globals.css";
import { DarkModeSwitch } from "@/components";

import { Inter } from "next/font/google";
import { cn } from "@/utils/cn";
import { ThemeProvider } from "next-themes";

// If loading a variable font, you don't need to specify the font weight
const inter = Inter({
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          // defaultTheme="system"
          storageKey="theme"
          enableSystem={true}
          enableColorScheme={true}
          disableTransitionOnChange = {false}
        >
          <main
            className={cn(
              "flex flex-col items-center",
              "bg-neutral-50 text-neutral-950",
              "dark:bg-neutral-950 dark:text-neutral-50",
            )}
          >
            <nav className="flex h-14 w-full items-center justify-between px-4">
              <DarkModeSwitch />
            </nav>
            {children}
          </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
