import type { Metadata } from "next";
import "./globals.css";
import { DarkModeSwitch } from "@/components";

import { Inter } from "next/font/google";
import { cn } from "@/utils/cn";
import { ThemeProvider } from "next-themes";

// If loading a variable font, you don't need to specify the font weight
const inter = Inter({
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          inter.className,
          "bg-primary-200 text-primary-950",
          "data-[theme=dark]:bg-primary-950 data-[theme=dark]:text-primary-50",
        )}
      >
        <ThemeProvider
          attribute="data-theme"
          // defaultTheme="system"
          storageKey="theme"
          enableSystem={true}
          enableColorScheme={true}
          disableTransitionOnChange={false}
        >
          <main className={cn("flex flex-col items-center", "w-screen")}>
            <nav
              className={cn(
                "flex h-14 w-full flex-row-reverse items-center justify-between px-4 shadow",
                "bg-primary-50 text-primary-950 shadow-primary-950/10",
                "data-[theme=dark]:bg-primary-950 data-[theme=dark]:text-primary-50 data-[theme=dark]:shadow-primary-50/10",
              )}
            >
              <DarkModeSwitch />
            </nav>
            {children}
          </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
